### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by Moosems** [not-nef/txt2#15]
Does txt2 ever plan to add code editing? I have been developing an ide myself so I could help implement that if you want. If you do want to add this and you want more than one language then the tab system might be an issue when it comes to using one text widget. Imo it is easier and better to create separate widgets for different languages which is why I'm redoing my ide to add specialized LangEditor widgets

**Comment by sumeshir26** [comment]
Nice! Is your code open source? Any help is always appriciated

**Comment by Moosems** [comment]
Yup! The link to the main website is [here](jde-org.github.io)!

**Comment by not-nef** [comment]
Sure!

**Comment by not-nef** [comment]
note for future me: https://github.com/rdbende/tkcode

**Comment by not-nef** [comment]
I think a better way of doing this is by using [pygments](https://github.com/pygments/pygments)

**Comment by not-nef** [comment]
Still have to look into how its used

**Comment by Moosems** [comment]
I know it a little bit

**Comment by not-nef** [comment]
Rdbende published chlorophyl which also provides a text widget based on pygments. But can we use it with the line numbers? @Moosems

**Comment by Moosems** [comment]
@not-nef I don't see a reason why not

**Comment by Moosems** [comment]
I was actually going to use tkcode/chlorophyll as a base anyway so that works perfect

**Comment by Moosems** [comment]
@not-nef If we use my idea of specialized widgets and changing the tab system to use a type of notebook then [this](https://github.com/not-nef/txt2/issues/8) could be done easier. When possible it's better to have less buttons and more keybinds. There could be a key bind for md files that creates a preview tab specialized for this

**Comment by not-nef** [comment]
#8 is actually pretty much done. And i dont think using a notebook looks that good.

**Comment by Moosems** [comment]
> i dont think using a notebook looks that good. 

What if we used sv_ttk's notebook? I can work on its performance capabilities

**Comment by not-nef** [comment]
@Moosems Could you please try to remove the proxy from chlorophyll? It is causing problems again. That would be so awesome!

**Comment by not-nef** [comment]
> > i dont think using a notebook looks that good. 
> 
> What if we used sv_ttk's notebook? I can work on its performance capabilities

Using a notebook would mean we need a text widget for every tab, which will significantly decrease performance. I think we should keep it the way it is at the moment.

**Comment by Moosems** [comment]
> @Moosems Could you please try to remove the proxy from chlorophyll? It is causing problems again. That would be so awesome!

I'll do my best. Since I used specific binds there are certain events that might not trigger the hoped event which might cause issues but I'll open a pr with the changes!

**Comment by sumeshir26** [comment]
We dont need a text witget for every tab. We can just put the text witget outside the noteboox frame and add change te text if the tab is switched

**Comment by not-nef** [comment]
But why should we? I see no benefit of doing that

**Comment by not-nef** [comment]
@Moosems You dont need to remove the proxy, i found a solution!

**Comment by sumeshir26** [comment]
> We dont need a text witget for every tab. We can just put the text witget outside the noteboox frame and add change te text if the tab is switched

Its easier to maintain, has less bugs, and can use all tkinter features

**Comment by not-nef** [comment]
If you guys want it, go ahead and add it. But i wont do it

**Comment by Moosems** [comment]
> @Moosems You dont need to remove the proxy, i found a solution!

Explain away my friend!

**Comment by Moosems** [comment]
> We dont need a text witget for every tab. We can just put the text witget outside the noteboox frame and add change te text if the tab is switched

Do we want to work on this together?

**Comment by not-nef** [comment]
> > @Moosems You dont need to remove the proxy, i found a solution!
> 
> Explain away my friend!

I changed it so it catches the error  and continues its job

**Comment by Moosems** [comment]
That's awesome. Thank you for that!!

**Comment by rdbende** [comment]
I think you don't even need to modify the proxy, since `Chlorophyll` handles pasting separately:

https://github.com/not-nef/txt2/blob/868dc688d2dd790411f044e94508c8a4b307ad00/src/widgets/codeview.py#L74-L82

**Comment by not-nef** [comment]
@rdbende its not about the pasting: when setting the sv_ttk theme after the widget is defined, the proxy throws an unknown option error.

**Comment by rdbende** [comment]
On what OS? I might be able to fix it in chlorophyll, but it doesn't happen for me.

**Comment by not-nef** [comment]
Windows 11, probably a windows issue

**Comment by rdbende** [comment]
Lemme test it.

**Comment by not-nef** [comment]
And the fix basically is catching the error, because it will continue to work anyway

**Comment by sumeshir26** [comment]
@Moosems Sure!

**Comment by Moosems** [comment]
@sumeshir26 Would you like to create the branch?

**Comment by sumeshir26** [comment]
im not free today, you go ahead and create the branch, will help from tommorow
