### ISSUE TITLE
Textwidget is too big on fonts other than helvetica

### ISSUE THREAD

**Issue by not-nef** [not-nef/txt2#16]

**Comment by Moosems** [comment]
Can you show the issue with a picture?

**Comment by not-nef** [comment]
Just switch the font to something other than helvetica and you will see that the footer is gone because the textwidget is too big

**Comment by Moosems** [comment]
Put the text widget in a frame so it doesn't expand. I also recommend we swap over to using grid()

**Comment by not-nef** [comment]
i dont like grid, its confusing. But thanks for the solution!

**Comment by Moosems** [comment]
I can translate it to grid. I hated it up until 4 weeks ago when it just clicked. It really is good if used correctly

**Comment by Moosems** [comment]
> I can translate it to grid. I hated it up until 4 weeks ago when it just clicked. It really is good if used correctly

@not-nef This will by my next pr
