### ISSUE TITLE
Menu Bar

### ISSUE THREAD

**Issue by sumeshir26** [not-nef/txt2#2]
This could be how it is implemented:
- A row of buttons in the top row with the `ToolButton` style (Like `File`, `Edit`, `About`, etc.)
- When one of the buttons is clicked, a small window with `overrideredirict` set to true opens where the mouse is currently located
- The small window would have a small column of `ToolButton`s with each action (Like `Save`, `Save As`, `Open`, etc.)
- Maybe there could be a `MenuButton` class with all of the above (tho you don't like classes so...)

**Comment by not-nef** [comment]
I think i found a way to do that more efficiently

![Screenshot 2022-07-01 194411](https://user-images.githubusercontent.com/83908932/176945046-d7948bec-d2db-4d2b-8822-90b76dc8dd71.png)

**Comment by sumeshir26** [comment]
Yeah, but the dropdown looks bad... You can use whatever way you like

**Comment by not-nef** [comment]
I think its alright
