### ISSUE TITLE
Rewrite tab system with ttk.Notebook

### ISSUE THREAD

**Issue by not-nef** [not-nef/txt2#21]
this can be done by adding a button when a new tab gets created instead of rebuilding the whole list

**Comment by not-nef** [comment]
@Moosems what do you think about that?

**Comment by Moosems** [comment]
I like it. When removing a tab, what if we just slide over the tabs rather than deleting them?

**Comment by not-nef** [comment]
Im afraid that would be too complicated

**Comment by not-nef** [comment]
@sumeshir26 @Moosems I have already started work on this. Will commit when its somewhat stable

**Comment by Moosems** [comment]
@not-nef Good to know
