### ISSUE TITLE
Drag and drop file into window to open it

### ISSUE THREAD

**Issue by not-nef** [not-nef/txt2#23]

**Comment by Moosems** [comment]
You want me to add this?

**Comment by not-nef** [comment]
If you want to

**Comment by Moosems** [comment]
Alright. What file types are allowed?

**Comment by sumeshir26** [comment]
I guess any type..

**Comment by not-nef** [comment]
Yea any type.

**Comment by Moosems** [comment]
Ok 😅

**Comment by HuyHung1408** [comment]
This gonna be a nice feature

**Comment by Moosems** [comment]
Oh my goodness I just realized I forgot to do this. I had been looking at tkdnd but wasn't super sure on if it was trustworthy or if it would really work. @not-nef what do you think of the module?

**Comment by not-nef** [comment]
I will use rdbendes tkdnd wrapper when implementing this, you can focus on the notebook system!
