### ISSUE TITLE
Add icons to settings tabs

### ISSUE THREAD

**Issue by not-nef** [not-nef/txt2#30]

**Comment by Moosems** [comment]
I can change it to an icon. I'll do this in my grid update

**Comment by not-nef** [comment]
can you wait with your grid thing please? i am currently working on the syntax highlighting.

**Comment by Moosems** [comment]
Got it

**Comment by Moosems** [comment]
> can you wait with your grid thing please? i am currently working on the syntax highlighting.

Can I change it to grid now?

**Comment by not-nef** [comment]
Yeah
