### ISSUE TITLE
Mica

### ISSUE THREAD

**Issue by sumeshir26** [not-nef/txt2#4]
The normal `win32mica` way...

**Comment by not-nef** [comment]
Not necessary because the text widget blocks most of the window and it would not look good

**Comment by sumeshir26** [comment]
But if I only add the mica to the menu bar and the footer, it looks sooo good:
![image](https://user-images.githubusercontent.com/68823982/177028050-65ebc578-f34a-4c77-8996-4126cdabcbbf.png)
(It kinda looks like windows 11 notepad now :) )

**Comment by not-nef** [comment]
Gonna make it an optional feature when the settings window is ready!

**Comment by sumeshir26** [comment]
sure! Should i open a PR?

**Comment by not-nef** [comment]
lets wait until i have the settings window ready ok?

**Comment by not-nef** [comment]
btw i gave you collaborator access so you can work directly on this repository

**Comment by sumeshir26** [comment]
ok np
