### ISSUE TITLE
Light mode doesn't work with Codeview

### ISSUE THREAD

**Issue by Moosems** [not-nef/txt2#46]
Need to make custom theme or use a builtin light theme

**Comment by Moosems** [comment]
@not-nef Don't use the custom Codeview because you can still make new themes with the regular CodeView. Using a custom one makes it difficult to stay up to date

**Comment by not-nef** [comment]
I had to make a custom one to fix an issue it had and to add linenumbers

**Comment by Moosems** [comment]
What issue? I use CodeView with tklinenums and it works just fine

**Comment by not-nef** [comment]
Idk there was some issue with the proxy

**Comment by Moosems** [comment]
Yeah the new codeview version fixed that

**Comment by not-nef** [comment]
Cool
