### ISSUE TITLE
Menu can't be dark in darkmode...?

### ISSUE THREAD

**Issue by sadjok** [not-nef/txt2#47]
Emmm, the menu of windows doesn't look like to be dark...?
Or just im wrong im just using windows10......
(Why windows11 need TPM....)

**Comment by not-nef** [comment]
Also you can bypass the windows 11 tpm requirement.

**Comment by sadjok** [comment]
So the menubar of windows can not change the background?

**Comment by sadjok** [comment]
Bypass the windows 11 tpm requirement?
How?
I buy my computer too early.... it only support tmp 1.4QAQ

**Comment by sadjok** [comment]
oh

**Comment by sadjok** [comment]
thx
