### ISSUE TITLE
from vars import *

### ISSUE THREAD

**Issue by not-nef** [not-nef/txt2#50]
Dont forget this you idiot

**Comment by not-nef** [comment]
I was standing at the register in the supermarket when this hit me. It would be so much better because it would completely eliminate the `v.` prefix!

**Comment by im-coder-lg** [comment]
My thought: Why is it that we get ideas at really weird timings?

Great comedic touch, I surely would do the same. You need any help on this?

**Comment by not-nef** [comment]
> My thought: Why is it that we get ideas at really weird timings?

Yeah right?

> You need any help on this?

Do you mean help with implementing it? I don't think so

**Comment by not-nef** [comment]
This doesnt work because the imported variables wont update

**Comment by sumeshir26** [comment]
What do you mean? It should work

**Comment by not-nef** [comment]
Ok, so we do `from vars import *` at the start of the script, and that will load the CURRENT state of the variables into the script, but the variables only get set later on in the main script, and the variables in vars.py get updated but not the ones that we loaded into the script at the beginning. Doing `v.root` for example will always get the current state for every call.
