### ISSUE TITLE
Line number improvements

### ISSUE THREAD

**Issue by Moosems** [not-nef/txt2#52]
@not-nef I recently created a text widget modified to have a crazy good linenumber system that dynamically resizes. I'm gonna create a repo but the current implementation in txt2 has a few issues (common in tk editors) that I fixed. I'll link the repo soon

**Comment by not-nef** [comment]
Yoo great!!

**Comment by Moosems** [comment]
@not-nef https://github.com/Moosems/TkLineNums It's on pypi to as `tklinenums`. Check the tests folder and copy paste the contents to a new file after downloading., That should give you a sense of the linenumbers. It's almost exactly the same as the current one but with a few improvements

**Comment by not-nef** [comment]
Great!

**Comment by Moosems** [comment]
Make sure you use version 1.3

**Comment by not-nef** [comment]
![image](https://user-images.githubusercontent.com/83908932/192024460-2976fbbe-873e-491c-b46d-9b30e8e58189.png)

**Comment by Moosems** [comment]
On pypi

**Comment by Moosems** [comment]
<img width="363" alt="Screen Shot 2022-09-23 at 1 38 41 PM" src="https://user-images.githubusercontent.com/95927277/192025545-505c5fac-081d-496a-8dab-5a3d0fa63189.png">
